# Generated by Django 4.2.2 on 2023-07-01 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('mc_id', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=200, null=True, unique=True)),
                ('emailVerified', models.DateTimeField(null=True)),
                ('image', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200, unique=True)),
                ('expires', models.DateTimeField()),
            ],
            options={
                'db_table': 'verificationtoken',
                'unique_together': {('identifier', 'token')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('sessionToken', models.CharField(max_length=200, unique=True)),
                ('expires', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('native_lan', models.CharField(max_length=20)),
                ('foreign_lan', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Thuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('providerAccountId', models.CharField(max_length=200)),
                ('refresh_token', models.TextField(max_length=1000, null=True)),
                ('access_token', models.TextField(max_length=1000, null=True)),
                ('expires_at', models.IntegerField(null=True)),
                ('token_type', models.CharField(max_length=200, null=True)),
                ('scope', models.CharField(max_length=200, null=True)),
                ('id_token', models.TextField(max_length=1000, null=True)),
                ('session_state', models.CharField(max_length=200, null=True)),
                ('oauth_token_secret', models.CharField(max_length=200, null=True)),
                ('oauth_token', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'account',
                'unique_together': {('provider', 'providerAccountId')},
            },
        ),
    ]
