# Generated by Django 4.2.2 on 2023-07-23 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_language_remove_profile_foreign_lan_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
        migrations.AlterModelTable(
            name='session',
            table='Session',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
        migrations.AlterModelTable(
            name='verificationtoken',
            table='VerificationToken',
        ),
    ]
