# Generated by Django 4.2.2 on 2023-08-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_nationality_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='nationality',
            old_name='name',
            new_name='code',
        ),
        migrations.AddField(
            model_name='language',
            name='label',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nationality',
            name='label',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
