# Generated by Django 4.2.2 on 2023-07-02 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_language_remove_profile_foreign_lan_and_more'),
        ('swipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('swipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='swipes.swipe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='accounts.user')),
            ],
        ),
        migrations.AddField(
            model_name='swipe',
            name='matched',
            field=models.ManyToManyField(blank=True, related_name='matched', through='swipes.Match', to='accounts.user'),
        ),
    ]
