export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const AUTEHNTICATED_FAIL = 'AUTHENTICATED_FAIL'
export const PASSWORD_RESET_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const PASSWORD_RESET_FAIL = 'AUTHENTICATED_FAIL'
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const PASSWORD_RESET_CONFIRM_FAIL = 'AUTHENTICATED_FAIL'
export const LOG_OUT = 'LOG_OUT'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS'
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL'
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAIL = 'DELTE_ACCOUNT_FAIL'

export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS'
export const PROFILE_CREATE_FAIL = 'PROFILE_CREATE_FAIL'
export const PROFILE_RECEIVE_SUCCESS = 'PROFILE_RECEIVE_SUCCESS'
export const PROFILE_RECEIVE_FAIL = 'PROFILE_RECEIVE_FAIL'
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL'
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS'
export const PROFILE_DELETE_FAIL = 'PROFILE_DELETE_FAIL'


export const IMGAE_CREATE_SUCCESS = 'IMGAE_CREATE_SUCCESS'
export const IMAGE_CREATE_FAIL = 'IMAGE_CREATE_FAIL'
export const IMAGE_RECEIVE_SUCCESS = 'IMAGE_RECEIVE_SUCCESS'
export const IMAGE_RECEIVE_FAIL = 'IMAGE_RECEIVE_FAIL'
export const IMAGE_DELETE_SUCCESS = 'IMAGE_DELETE_SUCCESS'
export const IMAGE_DELETE_FAIL = 'IMAGE_DELETE_FAIL'


export const SWIPE_CREATE_SUCCESS = 'SWIPE_CREATE_SUCCESS'
export const SWIPE_CREATE_FAIL = 'SWIPE_CREATE_FAIL'
export const SWIPE_RECEIVE_SUCCESS = 'SWIPE_RECEIVE_SUCCESS'
export const SWIPE_RECEIVE_FAIL = 'SWIPE_RECEIVE_FAIL'
export const SWIPE_UPDATE_SUCCESS = 'SWIPE_UPDATE_SUCCESS'
export const SWIPE_UPDATE_FAIL = 'SWIPE_UPDATE_FAIL'
export const SWIPE_DELETE_SUCCESS = 'SWIPE_DELETE_SUCCESS'
export const SWIPE_DELETE_FAIL = 'SWIPE_DELETE_FAIL'
export const CARD_RECEIVE_SUCCESS = 'CARD_RECEIVE_SUCCESS'
export const CARD_RECEIVE_FAIL = 'CARD_RECEIVE_FAIL'

export const CHAT_CREATE_SUCCESS = 'CHAT_CREATE_SUCCESS'
export const CHAT_CREATE_FAIL = 'CHAT_CREATE_SUCCESS'
export const CHAT_FETCH_MESSAGES_SUCCESS = 'CHAT_FETCH_MESSAGES_SUCCESS'
export const CHAT_FETCH_MESSAGES_FAIL = 'CHAT_FETCH_MESSAGES_FAIL'
export const CHAT_NEW_MESSAGE_SUCCESS = 'CHAT_NEW_MESSAGE_SUCCESS'
export const CHAT_NEW_MESSAGE_FAIL = 'CHAT_NEW_MESSAGE_FAIL'
export const CHAT_DELETE_SUCCESS = 'CHAT_DELETE_SUCCESS'
export const CHAT_DELETE_FAIL = 'CHAT_DELETE_FAIL'
export const CHAT_FETCH_FILES_SUCCESS = 'CHAT_FETCH_FILES_SUCCESS'
export const CHAT_FETCH_FILES_FAIL = 'CHAT_FETCH_FILES_FAIL'
export const CHAT_NEW_FILE_SUCCESS = 'CHAT_NEW_FILE_SUCCESS'
export const CHAT_NEW_FILE_FAIL = 'CHAT_NEW_FILE_FAIL'
export const BACK_TO_CHATPANEL = 'BACK_TO_CHATPANEL'
export const SET_FRIEND = 'SET_FRIEND'
export const GET_FRIEND_PROFILE = 'GET_FRIEND_PROFILE'
export const SEND_FIRST_MESSAGE_SUCCESS = 'SEND_FIRST_MESSAGE_SUCCESS'
export const SEND_FIRST_MESSAGE_FAIL = 'SEND_FIRST_MESSAGE_FAIL'

export const CONTACT_CREATE_SUCCESS = 'CONTACT_CREATE_SUCCESS'
export const CONTACT_CREATE_FAIL = 'CONTACT_CREATE_FAIL'
export const CONTACT_RECEIVE_SUCCESS = 'CONTACT_RECEIVE_SUCCESS'
export const CONTACT_RECEIVE_FAIL = 'CONTACT_RECEIVE_FAIL'
export const CONTACT_UPDATE_SUCCESS = 'CONTACT_UPDATE_SUCCESS'
export const CONTACT_UPDATE_FAIL = 'CONTACT_UPDATE_FAIL'
export const CONTACT_DELETE_SUCCESS = 'CONTACT_DELETE_SUCCESS'
export const CONTACT_DELETE_FAIL = 'CONTACT_DELETE_FAIL'

export const ERROR = "ERROR"
export const REMOVE_ERROR = "REMOVE_ERROR"
export const BACK_TO_HOME = "BACK_TO_HOME"

export default function null_checker(prop) {
    if (prop === 'null' || prop === '') {
        prop = null;
    }
    return prop
}