# Generated by Django 3.1.1 on 2020-12-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_auto_20201229_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
