# Generated by Django 3.1.1 on 2021-01-01 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_file_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
    ]
